baseURL = 'https://matheuskid.github.io/portifolio'
locale = 'pt-br'
title = 'matheuskid@portifolio:-$'
theme = 'terminal'

[markup.goldmark.renderer]
    unsafe = true

[languages.en.params.logo]
    logoText = "matheuskid@portifolio:-$"
    logoHomeLink = "/"
