baseURL = "https://matheuskid.github.io/portifolio/"
locale = 'pt-br'
title = 'matheuskid@portifolio:-$'
theme = 'terminal'

[markup.goldmark.renderer]
    unsafe = true

[params.logo]
    logoText = "matheuskid@portifolio:-$"
    logoHomeLink = "/portifolio"

[[menus.main]]
    name = "Github"
    url = "https://github.com/matheuskid"
    [menus.main.params]
        NewTab = true

[[menus.main]]
    name = "Linkedin"
    url = "https://www.linkedin.com/in/matheus-mendes-275b04210/"
    [menus.main.params]
        NewTab = true
